- hosts: localhost
  vars:
    apps: [
      {"name": "权限配置服务", "url": "http://alinesno-infra-base-authority-ui.beta.base.infra.linesno.com" },
      {"name": "代码生成器", "url": "http://alinesno-infra-base-starter-ui.beta.base.infra.linesno.com" },
      {"name": "分布式配置服务", "url": "http://alinesno-infra-base-config-ui.beta.base.infra.linesno.com" },
      {"name": "事务消息服务", "url": "http://alinesno-infra-base-message-ui.beta.base.infra.linesno.com" },
      {"name": "通知管理服务", "url": "http://alinesno-infra-base-notice-ui.beta.base.infra.linesno.com" },
      {"name": "存储管理服务", "url": "http://alinesno-infra-base-storage-ui.beta.base.infra.linesno.com" },
      {"name": "单点登陆服务", "url": "http://alinesno-infra-base-identity-ui.beta.base.infra.linesno.com" },
      {"name": "网关配置服务", "url": "http://alinesno-infra-base-gateway-ui.beta.base.infra.linesno.com" },
      {"name": "安全验证码服务", "url": "http://alinesno-infra-base-validate-ui.beta.base.infra.linesno.com" },
      {"name": "IM消息服务", "url": "http://alinesno-infra-base-im-ui.beta.base.infra.linesno.com" },
      {"name": "邮箱管理服务", "url": "http://alinesno-infra-base-email-ui.beta.base.infra.linesno.com" },
      {"name": "向量库搜索服务", "url": "http://alinesno-infra-base-search-ui.beta.base.infra.linesno.com" },
      {"name": "分布式ID服务", "url": "http://alinesno-infra-base-id-ui.beta.base.infra.linesno.com" },
      {"name": "敏感词过滤服务", "url": "http://alinesno-infra-base-sensitive-ui.beta.base.infra.linesno.com" },
      {"name": "支付服务", "url": "http://alinesno-infra-base-pay-ui.beta.base.infra.linesno.com" },
      {"name": "会员服务", "url": "http://alinesno-infra-base-member-ui.beta.base.infra.linesno.com" },
      {"name": "内容管理系统服务", "url": "http://alinesno-infra-base-cms-ui.beta.base.infra.linesno.com" },
      {"name": "基础商品管理服务", "url": "http://alinesno-infra-base-shop-ui.beta.base.infra.linesno.com" },
      {"name": "流程中心服务", "url": "http://alinesno-infra-base-workflow-ui.beta.base.infra.linesno.com" },
      {"name": "文档查看服务", "url": "http://alinesno-infra-base-fileshow-ui.beta.base.infra.linesno.com" },
      {"name": "主数据服务", "url": "http://alinesno-infra-data-mdm-ui.beta.data.infra.linesno.com" },
      {"name": "数据上报服务", "url": "http://alinesno-infra-data-report-ui.beta.data.infra.linesno.com" },
      {"name": "数据集成服务", "url": "http://alinesno-infra-data-pipeline-ui.beta.data.infra.linesno.com" },
      {"name": "数据编排计算服务", "url": "http://alinesno-infra-data-dolphinscheduler-ui.beta.data.infra.linesno.com" },
      {"name": "实时计算服务", "url": "http://alinesno-infra-data-stream-ui.beta.data.infra.linesno.com" },
      {"name": "数据安全服务", "url": "http://alinesno-infra-data-security-ui.beta.data.infra.linesno.com" },
      {"name": "数据质量服务", "url": "http://alinesno-infra-data-quality-ui.beta.data.infra.linesno.com" },
      {"name": "数据总线服务", "url": "http://alinesno-infra-data-bus-ui.beta.data.infra.linesno.com" },
      {"name": "数据资产服务", "url": "http://alinesno-infra-data-assets-ui.beta.data.infra.linesno.com" },
      {"name": "数据算法服务", "url": "http://alinesno-infra-data-algorithm-ui.beta.data.infra.linesno.com" },
      {"name": "数据接口服务", "url": "http://alinesno-infra-data-fastapi-ui.beta.data.infra.linesno.com" },
      {"name": "OCR视觉识别服务", "url": "http://alinesno-infra-smart-ocr-ui.beta.smart.infra.linesno.com" },
      {"name": "自然语言识别服务", "url": "http://alinesno-infra-smart-nlp-ui.beta.smart.infra.linesno.com" },
      {"name": "大模型推理服务", "url": "http://alinesno-infra-smart-brain-ui.beta.smart.infra.linesno.com" },
      {"name": "流媒体识别服务", "url": "http://alinesno-infra-smart-media-ui.beta.smart.infra.linesno.com" },
      {"name": "智能助手服务", "url": "http://alinesno-infra-smart-assistant-ui.beta.smart.infra.linesno.com" },
      {"name": "目标检测识别服务", "url": "http://alinesno-infra-smart-detection-ui.beta.smart.infra.linesno.com" },
      {"name": "自动化任务服务", "url": "http://alinesno-infra-ops-scheduler-ui.beta.base.infra.linesno.com" },
      {"name": "分布式日志服务", "url": "http://alinesno-infra-ops-logback-ui.beta.base.infra.linesno.com" },
      {"name": "分布式链路跟踪服务", "url": "http://alinesno-infra-ops-telemetry-ui.beta.base.infra.linesno.com" },
      {"name": "持续集成服务", "url": "http://alinesno-infra-ops-pipeline-ui.beta.base.infra.linesno.com" },
      {"name": "容器管理服务", "url": "http://alinesno-infra-ops-container-ui.beta.base.infra.linesno.com" },
      {"name": "监控预警服务", "url": "http://alinesno-infra-ops-watcher-ui.beta.base.infra.linesno.com" },
      {"name": "商品秒杀服务", "url": "http://alinesno-infra-bus-limit-ui.beta.data.infra.linesno.com" },
      {"name": "实时推荐服务", "url": "http://alinesno-infra-bus-recommend-ui.beta.data.infra.linesno.com" },
      {"name": "实时画像服务", "url": "http://alinesno-infra-bus-profiling-ui.beta.data.infra.linesno.com" },
      {"name": "无代码开发服务", "url": "http://alinesno-infra-bus-nocode-ui.beta.data.infra.linesno.com" },
      {"name": "安全感触服务", "url": "http://alinesno-infra-plat-security-ui.beta.plat.infra.linesno.com" },
      {"name": "智能运营大脑服务", "url": "http://alinesno-infra-plat-security-ui.beta.plat.infra.linesno.com" },
      {"name": "基设平台管理服务", "url": "http://alinesno-infra-base-platform-ui.beta.base.infra.linesno.com" },
      {"name": "项目管理服务", "url": "http://alinesno-infra-plat-project-ui.beta.plat.infra.linesno.com" },
      {"name": "认证授权服务", "url": "http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com" }
    ]

  tasks:

    - name: 验证链接地址端口是否正常
      uri:
        url: "{{ item.url }}"
        timeout: 10
        return_content: no
        follow_redirects: safe
        validate_certs: yes
      with_items: "{{ apps }}"
      register: app_status
      ignore_errors: true

    - name: 生成异常json文件
      set_fact:
        failed_apps: "{{ app_status.results | rejectattr('failed', 'eq', False) | list }}"
      when: app_status.results | rejectattr('failed', 'eq', False) | list  | length > 0

    - name: 检测到异常应用信息
      debug:
        msg: |
          以下应用检测异常:
          {% for app in failed_apps %}
          {{ app.item.name }} 地址: ({{ app.item.url}}) \n
          {% endfor %}
      when: failed_apps is defined and failed_apps | length > 0

    - name: Send DingTalk notification
      uri:
        url: "{{ dingtalk_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          msgtype: "markdown"
          markdown:
            title: "应用存活状态检测"
            text: |
              ### 应用存活状态检测
              ---
              以下应用检测异常:
              {% for app in failed_apps %}
              - {{ app.item.name }} ({{ app.item.url}})
              {% endfor %}
      when: app_status.results | rejectattr('failed', 'eq', False) | list  | length > 0

    - name: Save JSON report for failed apps
      ansible.builtin.copy:
        content: "{{ failed_apps | to_nice_json }}"
        dest: "./failed_apps.json"
      when: failed_apps is defined and failed_apps | length > 0
