# # 定义一个名称为"Db Mysql Uat Backup"的工作流
# name: Db Mysql Uat Backup

# # 触发工作流的条件
# on:
#   # 当代码推送到"main"分支时触发
#   push:
#     branches:
#       - main
#   # 按照cron表达式定时触发
#   schedule:
#     # 每天下午4点（UTC时间）触发
#     - cron: "0 16 * * *"

# # 设置环境变量
# env:
#   # 设置时区为上海
#   TZ: Asia/Shanghai

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: SetUp Jdk17
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'zulu' # See 'Supported distributions' for available options
#           java-version: '17'

#       - name: Run a multi-line script
#         run: |
#           echo "Hello, world!"
