# # 同步 Github 仓库到 Gitee
# # 每天晚上 1 点自动触发同步操作
# name: Alinesno Tool To Release Demo

# on:
#   push:
#     branches:
#       - main  # 或者其他分支名

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       # steps for building assets
#       - run: echo "REPLACE ME!" > assets.txt

#       - name: Create a Release
#         id: create_release
#         uses: shogo82148/actions-create-release@v1

#       - name: Upload Assets
#         uses: shogo82148/actions-upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: assets.txt
